import { UserProvider } from "@/redux/usercontext";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
        {children}
        <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
